version: "3"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/myapp
      - /myapp/node_modules
    ports:
      - 5173:5173
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/myapp
      - /myapp/node_modules
    expose:
      - 8080
    environment:
      - MONGODB_URL=${MONGODB_URL}
    restart: always
